/**
 * WelcomeController.js
 *
 * @description :: Server-side logic for managing logged users.
 */

module.exports = {

  index: function(req, res, next){
    if(req.session.passport.user === undefined){ res.redirect('/login');}
    else
      res.render('api/index', {title: 'hello-world', description: 'page generated by API::WelcomeController::index'});
    //console.log (req.session.passport);
    /*return res.render('index', { title: 'Hello world', description: '<< this page is generated by WelcomeController >>' });*/
  }
}
